<?xml version="1.0" encoding="utf-8"?><Database Name="AuthorDB" Class="DataAuthorOrmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\AuthorDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AuthorDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Author" Member="Authors">
    <Type Name="Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fornavn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Etternavn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobil" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Author_News" Member="News" ThisKey="Id" OtherKey="AuthorID" Type="New" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tittel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tekst" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DatoPostet" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BildeSrc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Author_News" Member="Author" ThisKey="AuthorID" OtherKey="Id" Type="Author" IsForeignKey="true" />
    </Type>
  </Table>
</Database>